### PR TITLE
Add TLS 1.3 support.

### PR DESCRIPTION
**Pull request by lkarsten**
Compiles, tests fine, but has not seen live traffic.

### CODE REVIEW

**Comment by lkarsten** [comment]
Bump.

**Comment by bogi788** [comment]
I believe the line
`"TLSv1.3"       { return (TOK_TLSv1_3); }`
is missing in cfg_lex.l in order to parse configuration files with TLSv1.3.

**Comment by lkarsten** [comment]
Looks like this is in place in git master now. Any chance for cutting a release? :)

**Comment by daghf** [comment]
Closing. Thanks @lkarsten 

We are very very close to cutting a release now. :-)

**Pull request closed without merging**
