### PR TITLE
Fixes issues when compiling with non glibc

### PR DESCRIPTION
**Pull request by ktk**
This fixes an error I got on Alpine Linux like:

```
hitch.c:2444:8: error: assignment of read-only variable 'stdin'
  stdin = fopen(NULL_DEV, "r");
```
Still doesn't compile though but I don't know enough for the other issues. I think it's because Alpine Linux is using musl libc/busybox as base.

### CODE REVIEW

**Comment by ktk** [comment]
I correct with this patch latest Github version compiles on Alpine Linux.

**Comment by ktk** [comment]
Some of the pull-requests were apparently merged by @daghf but not this one. Is there any particular reason against/problem with this one?

**Comment by daghf** [comment]
Hi - sorry to keep you waiting so long. fc2c122 has now been merged. Thanks for the contribution!

**Comment by ktk** [comment]
Fantastic, thanks for the merge!

**Pull request closed without merging**
