### PR TITLE
Add Authority proxy header to allow detecting fronting with hitch <=> varnish duo

### PR DESCRIPTION
**Pull request by xdecock**
Having implemented a fronting detection algorithm in varnish, i've been confronted to the absence of support in hitch.

This should solve that oversight.

### CODE REVIEW

**Comment by xdecock** [comment]
Have issue with the 06 test, but i don't understand why as no code will cause issue on that level

**Comment by Dridi** [comment]
Does your test failure look like #292?

**Comment by xdecock** [comment]
No clue don't have the issue in local the test failing is the one about ticket i probably don't have the library. Only the docker ci

**Comment by Dridi** [comment]
Can you share the failing test log? When you run make check it should be available in `$(top_builddir)/src/tests/test06-ticket-resume.log`.

**Comment by xdecock** [comment]
[test06-ticket-resume.log](https://github.com/varnish/hitch/files/3165564/test06-ticket-resume.log)


I suspect it's because it should be skipped (as i haven't bootstrap with sessions)

and I took a long time to find the make check (i was expecting make tests?) so might be a good idea to add this to the doc. (i can make a pr for that if needed)

**Comment by Dridi** [comment]
The feature you are referring to is different, your failure looks definitely like #292. What system(s) is your CI running?

FYI, I am reviewing your pull request and besides code style violations it looks good. But before I can merge it I found a couple things to tidy up and I need review other areas too.

**Comment by xdecock** [comment]
My own laptop on Ubuntu 19.04

xavier@xavier-ThinkPad-X1-Carbon-6th:~$ openssl version
OpenSSL 1.1.1b  26 Feb 2019

And openssl s_client -sess_out test.txt www.google.com:443 do provide a session parameter, let me know if i can help on this one (it also fails on master)

**Comment by Dridi** [comment]
Don't worry about code style, I already have your changes locally, and while I'm reviewing and tidying up other parts of the code I'm making sure that I don't break your changes. I will push them manually because I'm introducing merge conflict you shouldn't have to deal with.

**Pull request closed without merging**
