### PR TITLE
Build system overhaul

### PR DESCRIPTION
**Pull request by Dridi**
Problems I'm trying to improve:

- autotools usage
- portability
- dependencies detection/usage
- compilation flags

Some of the work is already in master, more to come. It works on my system with 3 different compilers, I'm waiting to see whether older toolchains on Travis CI will also pass. This is based on previous work in cashpack.

### CODE REVIEW

**Comment by Dridi** [comment]
I tested the pull request on SmartOS and it wasn't enough. I just added 45ff453 to fix that.

**Comment by Dridi** [comment]
I think I'm done hunting portability issues, there's still one hard-coded `-Werror` flag which I intend to relocate later.

**Comment by daghf** [comment]
Excellent stuff, @Dridi - merged.

Newish automake versions seem to enforce a naming convention for `_LIBRARIES`:

<pre>
src/Makefile.am:3: error: 'cfg.a' is not a standard library name
src/Makefile.am:3: did you mean 'libcfg.a'?
src/Makefile.am:3: error: 'foreign.a' is not a standard library name
src/Makefile.am:3: did you mean 'libforeign.a'?
</pre>

this is automake 1.15

**Comment by Dridi** [comment]
Yes, I have seen this complaint, and I'm glad you're bringing this up.

This being a private privaty use of static libraries that aren't meant to be installed, I don't mind the warning. At the same time it prevents us from configuring `automake` with `-Wall` and `-Werror`. I really have no opinion on what TheRightThing(tm) should be, I'll make it your call. Getting rid of the warning sounds sensible :)

**Pull request merged**
